locations = ['Brunnenstr. Süd', 'Prenzlauer Berg Nordwest',
       'Prenzlauer Berg Südwest', 'Schöneberg-Nord', 'Helmholtzplatz',
       'Frankfurter Allee Süd FK', 'nördliche Luisenstadt',
       'Reuterstraße', 'südliche Luisenstadt', 'Tempelhofer Vorstadt',
       'Prenzlauer Berg Süd', 'Moabit Ost', 'Prenzlauer Berg Nord',
       'Otto-Suhr-Allee', 'Schillerpromenade', 'Alt  Treptow',
       'Alexanderplatz', 'Neue Kantstraße', 'Ostpreußendamm',
       'Schmöckwitz/Karolinenhof/Rauchfangswerder',
       'Neuköllner Mitte/Zentrum', 'Frankfurter Allee Nord', 'Kantstraße',
       'Schmargendorf', 'Regierungsviertel', 'Schöneberg-Süd',
       'Blankenfelde/Niederschönhausen', 'Friedrichshagen',
       'Südliche Friedrichstadt', 'Moabit West', 'Wiesbadener Straße',
       'West 3', 'Blankenburg/Heinersdorf/Märchenland',
       'Rummelsburger Bucht', 'Friedenau', 'Brunnenstr. Nord', 'Ost 2',
       'Volkspark Wilmersdorf', 'Pankow Zentrum', 'Pankow Süd',
       'Osloer Straße', 'Drakestr.', 'West 1', 'Prenzlauer Berg Ost',
       'Buckow Nord', 'Karlshorst', 'Karl-Marx-Allee-Nord',
       'Alt-Lichtenberg', 'Düsseldorfer Straße', 'Zehlendorf  Nord',
       'Tiergarten Süd', 'Neu Lichtenberg', 'Rudow', 'Mierendorffplatz',
       'Wedding Zentrum', 'Karl-Marx-Allee-Süd', 'Altglienicke',
       'Lichtenrade', 'Westend', 'Mahlsdorf', 'West 5', 'Rixdorf',
       'Biesdorf', 'Zehlendorf  Südwest', 'Johannisthal', 'West 2',
       'Barstraße', 'Marienfelde', 'Heerstraße Nord', 'Albrechtstr.',
       'Buckow', 'Baumschulenweg', 'Halensee', 'Schloß Charlottenburg',
       'Kurfürstendamm', 'Schloßstr.', 'Nord 1', 'Karow', 'Nord 2',
       'Tempelhof', 'Rahnsdorf/Hessenwinkel', 'Gatow / Kladow',
       'Lankwitz', 'Parkviertel', 'Alt-Hohenschönhausen Süd', 'Weißensee',
       'Schönholz/Wilhelmsruh/Rosenthal', 'Weißensee Ost',
       'Alt-Hohenschönhausen Nord', 'Gropiusstadt', 'Britz', 'Ost 1',
       'Kaulsdorf', 'Hellersdorf-Nord', 'Marzahn-Mitte', 'MV 1',
       'Adlershof', 'Heerstrasse', 'Teltower Damm', 'Wilhelmstadt',
       'Köllnische Heide', 'Frankfurter Allee Süd',
       'Friedrichsfelde Nord', 'Grunewald', 'Plänterwald', 'Buchholz',
       'West 4', 'Fennpfuhl', 'Köpenick-Nord', 'Bohnsdorf', 'Mariendorf',
       'MV 2', 'Marzahn-Süd', 'Siemensstadt', 'Müggelheim',
       'Charlottenburg Nord', 'Oberschöneweide', 'Buch',
       'Niederschöneweide', 'Spandau Mitte', 'Dammvorstadt',
       'Brunsbütteler Damm', 'Hakenfelde', 'Köpenick-Süd',
       'Neu-Hohenschönhausen Nord', 'Hellersdorf-Süd', 'Grünau',
       'Falkenhagener Feld', 'Haselhorst', 'Altstadt-Kietz',
       'Friedrichsfelde Süd', 'Neu-Hohenschönhausen Süd',
       'Malchow, Wartenberg und Falkenberg',
       'Kölln. Vorstadt/Spindlersf.', 'Hellersdorf-Ost',
       'Allende-Viertel']

property_type = ['Other', 'Apartment', 'House']




